'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    // Obtener todas las marcas con su id
    const [results] = await queryInterface.sequelize.query(
      `SELECT id, nombre FROM Marcas`
    );

    if (!results.length) {
      throw new Error('No se encontraron marcas. Asegúrate de haber ejecutado el seeder de marcas primero.');
    }

    // Crear un mapa nombre -> id
    const marcaIdMap = {};
    for (const marca of results) {
      if (marca.nombre && marca.id) {
        marcaIdMap[marca.nombre.trim()] = marca.id;
      }
    }

    const modelos = [
      

      // Modelos de Alfa Romeo
      { nombre: '145', marca: 'Alfa Romeo' },
      { nombre: '147', marca: 'Alfa Romeo' },
      { nombre: '155', marca: 'Alfa Romeo' },
      { nombre: '156', marca: 'Alfa Romeo' },
      { nombre: '159', marca: 'Alfa Romeo' },
      { nombre: '164', marca: 'Alfa Romeo' },
      { nombre: '166', marca: 'Alfa Romeo' },
      { nombre: 'Brera', marca: 'Alfa Romeo' },
      { nombre: 'Giulia', marca: 'Alfa Romeo' },
      { nombre: 'Giulietta', marca: 'Alfa Romeo' },
      { nombre: 'Gt', marca: 'Alfa Romeo' },
      { nombre: 'Gtv', marca: 'Alfa Romeo' },
      { nombre: 'Mito', marca: 'Alfa Romeo' },
      { nombre: 'Stelvio', marca: 'Alfa Romeo' },

      // Modelos de Audi
{ nombre: 'A1', marca: 'Audi' },
{ nombre: 'A3', marca: 'Audi' },
{ nombre: 'A4', marca: 'Audi' },
{ nombre: 'A4 Allroad Quattro', marca: 'Audi' },
{ nombre: 'A5', marca: 'Audi' },
{ nombre: 'A6', marca: 'Audi' },
{ nombre: 'A6 Allroad Quattro', marca: 'Audi' },
{ nombre: 'A7', marca: 'Audi' },
{ nombre: 'A8', marca: 'Audi' },
{ nombre: 'E-Tron Gt', marca: 'Audi' },
{ nombre: 'E-Tron Sportback', marca: 'Audi' },
{ nombre: 'Q2', marca: 'Audi' },
{ nombre: 'Q3', marca: 'Audi' },
{ nombre: 'Q3 Sportback', marca: 'Audi' },
{ nombre: 'Q5', marca: 'Audi' },
{ nombre: 'Q5 Sportback', marca: 'Audi' },
{ nombre: 'Q7', marca: 'Audi' },
{ nombre: 'Q8', marca: 'Audi' },
{ nombre: 'R8', marca: 'Audi' },
{ nombre: 'Rs Q3', marca: 'Audi' },
{ nombre: 'Rs3', marca: 'Audi' },
{ nombre: 'Rs4', marca: 'Audi' },
{ nombre: 'Rs5', marca: 'Audi' },
{ nombre: 'Rs6', marca: 'Audi' },
{ nombre: 'Rsq8', marca: 'Audi' },
{ nombre: 'S3', marca: 'Audi' },
{ nombre: 'S4', marca: 'Audi' },
{ nombre: 'S5', marca: 'Audi' },
{ nombre: 'S6', marca: 'Audi' },
{ nombre: 'S7', marca: 'Audi' },
{ nombre: 'S8', marca: 'Audi' },
{ nombre: 'Sq5', marca: 'Audi' },
{ nombre: 'Tt', marca: 'Audi' },
{ nombre: 'Tt Coupé', marca: 'Audi' },
{ nombre: 'Tt Roadster', marca: 'Audi' },
{ nombre: 'Tts', marca: 'Audi' },

// Modelos de BMW
{ nombre: '114', marca: 'BMW' },
{ nombre: '116', marca: 'BMW' },
{ nombre: '116I', marca: 'BMW' },
{ nombre: '116I SPORT', marca: 'BMW' },
{ nombre: '118', marca: 'BMW' },
{ nombre: '120', marca: 'BMW' },
{ nombre: '125', marca: 'BMW' },
{ nombre: '128', marca: 'BMW' },
{ nombre: '128ti', marca: 'BMW' },
{ nombre: '135', marca: 'BMW' },
{ nombre: '140', marca: 'BMW' },
{ nombre: '218', marca: 'BMW' },
{ nombre: '220', marca: 'BMW' },
{ nombre: '235', marca: 'BMW' },
{ nombre: '240I', marca: 'BMW' },
{ nombre: '240M', marca: 'BMW' },
{ nombre: '315', marca: 'BMW' },
{ nombre: '316', marca: 'BMW' },
{ nombre: '318', marca: 'BMW' },
{ nombre: '320', marca: 'BMW' },
{ nombre: '320I', marca: 'BMW' },
{ nombre: '323', marca: 'BMW' },
{ nombre: '325', marca: 'BMW' },
{ nombre: '328', marca: 'BMW' },
{ nombre: '330', marca: 'BMW' },
{ nombre: '335', marca: 'BMW' },
{ nombre: '340', marca: 'BMW' },
{ nombre: '418', marca: 'BMW' },
{ nombre: '420', marca: 'BMW' },
{ nombre: '428', marca: 'BMW' },
{ nombre: '430', marca: 'BMW' },
{ nombre: '435', marca: 'BMW' },
{ nombre: '440', marca: 'BMW' },
{ nombre: '518', marca: 'BMW' },
{ nombre: '520', marca: 'BMW' },
{ nombre: '523', marca: 'BMW' },
{ nombre: '525', marca: 'BMW' },
{ nombre: '528', marca: 'BMW' },
{ nombre: '530', marca: 'BMW' },
{ nombre: '535', marca: 'BMW' },
{ nombre: '540', marca: 'BMW' },
{ nombre: '550', marca: 'BMW' },
{ nombre: '630', marca: 'BMW' },
{ nombre: '640', marca: 'BMW' },
{ nombre: '645', marca: 'BMW' },
{ nombre: '650', marca: 'BMW' },
{ nombre: '730', marca: 'BMW' },
{ nombre: '740', marca: 'BMW' },
{ nombre: '745', marca: 'BMW' },
{ nombre: '750', marca: 'BMW' },
{ nombre: 'I3', marca: 'BMW' },
{ nombre: 'I4', marca: 'BMW' },
{ nombre: 'I5', marca: 'BMW' },
{ nombre: 'I7', marca: 'BMW' },
{ nombre: 'I8', marca: 'BMW' },
{ nombre: 'Isseta', marca: 'BMW' },
{ nombre: 'Ix', marca: 'BMW' },
{ nombre: 'Ix1', marca: 'BMW' },
{ nombre: 'Ix2', marca: 'BMW' },
{ nombre: 'Ix3', marca: 'BMW' },
{ nombre: 'M1', marca: 'BMW' },
{ nombre: 'M2', marca: 'BMW' },
{ nombre: 'M235i', marca: 'BMW' },
{ nombre: 'M240', marca: 'BMW' },
{ nombre: 'M240i', marca: 'BMW' },
{ nombre: 'M3', marca: 'BMW' },
{ nombre: 'M340', marca: 'BMW' },
{ nombre: 'M4', marca: 'BMW' },
{ nombre: 'M4 Gts', marca: 'BMW' },
{ nombre: 'M440i', marca: 'BMW' },
{ nombre: 'M5', marca: 'BMW' },
{ nombre: 'M550', marca: 'BMW' },
{ nombre: 'M6', marca: 'BMW' },
{ nombre: 'M8 Competition', marca: 'BMW' },
{ nombre: 'Serie 1', marca: 'BMW' },
{ nombre: 'Serie 2', marca: 'BMW' },
{ nombre: 'Serie 3', marca: 'BMW' },
{ nombre: 'Serie 4', marca: 'BMW' },
{ nombre: 'Serie 5', marca: 'BMW' },
{ nombre: 'Serie 7', marca: 'BMW' },
{ nombre: 'Serie 8', marca: 'BMW' },
{ nombre: 'Serie 8 M850i Xdrive', marca: 'BMW' },
{ nombre: 'X1', marca: 'BMW' },
{ nombre: 'X2', marca: 'BMW' },
{ nombre: 'X3', marca: 'BMW' },
{ nombre: 'X3 XDRIVE 20D', marca: 'BMW' },
{ nombre: 'X4', marca: 'BMW' },
{ nombre: 'X5', marca: 'BMW' },
{ nombre: 'X6', marca: 'BMW' },
{ nombre: 'X7', marca: 'BMW' },
{ nombre: 'Z3', marca: 'BMW' },
{ nombre: 'Z4', marca: 'BMW' },

// Modelos de Chevrolet - LISTA SÚPER COMPLETA (70 modelos)
{ nombre: '51', marca: 'Chevrolet' },
{ nombre: 'Apache', marca: 'Chevrolet' },
{ nombre: 'Astro', marca: 'Chevrolet' },
{ nombre: 'Aveo', marca: 'Chevrolet' },
{ nombre: 'Bel Air', marca: 'Chevrolet' },
{ nombre: 'Blazer', marca: 'Chevrolet' },
{ nombre: 'Bolt EV', marca: 'Chevrolet' },
{ nombre: 'C10', marca: 'Chevrolet' },
{ nombre: 'C20', marca: 'Chevrolet' },
{ nombre: 'Camaro', marca: 'Chevrolet' },
{ nombre: 'Captiva', marca: 'Chevrolet' },
{ nombre: 'Cavalier', marca: 'Chevrolet' },
{ nombre: 'Celta', marca: 'Chevrolet' },
{ nombre: 'Chevelle', marca: 'Chevrolet' },
{ nombre: 'Chevy', marca: 'Chevrolet' },
{ nombre: 'Classic', marca: 'Chevrolet' },
{ nombre: 'Cobalt', marca: 'Chevrolet' },
{ nombre: 'Colorado', marca: 'Chevrolet' },
{ nombre: 'Corsa', marca: 'Chevrolet' },
{ nombre: 'Corvette', marca: 'Chevrolet' },
{ nombre: 'Cruze', marca: 'Chevrolet' },
{ nombre: 'D20', marca: 'Chevrolet' },
{ nombre: 'Dmax', marca: 'Chevrolet' },
{ nombre: 'El Camino', marca: 'Chevrolet' },
{ nombre: 'Epica', marca: 'Chevrolet' },
{ nombre: 'Equinox', marca: 'Chevrolet' },
{ nombre: 'Equinox Ev', marca: 'Chevrolet' },
{ nombre: 'Express', marca: 'Chevrolet' },
{ nombre: 'Groove', marca: 'Chevrolet' },
{ nombre: 'Impala', marca: 'Chevrolet' },
{ nombre: 'Joy', marca: 'Chevrolet' },
{ nombre: 'Kadett', marca: 'Chevrolet' },
{ nombre: 'Lumina', marca: 'Chevrolet' },
{ nombre: 'Luv', marca: 'Chevrolet' },
{ nombre: 'Malibu', marca: 'Chevrolet' },
{ nombre: 'Meriva', marca: 'Chevrolet' },
{ nombre: 'Montana', marca: 'Chevrolet' },
{ nombre: 'Monza', marca: 'Chevrolet' },
{ nombre: 'N400 Max', marca: 'Chevrolet' },
{ nombre: 'Nova', marca: 'Chevrolet' },
{ nombre: 'Onix', marca: 'Chevrolet' },
{ nombre: 'Onix Hb', marca: 'Chevrolet' },
{ nombre: 'Opala', marca: 'Chevrolet' },
{ nombre: 'Orlando', marca: 'Chevrolet' },
{ nombre: 'Pick-up', marca: 'Chevrolet' },
{ nombre: 'Prisma', marca: 'Chevrolet' },
{ nombre: 'S10', marca: 'Chevrolet' },
{ nombre: 'SS', marca: 'Chevrolet' },
{ nombre: 'Sail', marca: 'Chevrolet' },
{ nombre: 'Sail Hb', marca: 'Chevrolet' },
{ nombre: 'Silverado', marca: 'Chevrolet' },
{ nombre: 'Silverado 1500', marca: 'Chevrolet' },
{ nombre: 'Silverado 2500', marca: 'Chevrolet' },
{ nombre: 'Silverado 3500', marca: 'Chevrolet' },
{ nombre: 'Sonic', marca: 'Chevrolet' },
{ nombre: 'Spark', marca: 'Chevrolet' },
{ nombre: 'Spin', marca: 'Chevrolet' },
{ nombre: 'Stepside', marca: 'Chevrolet' },
{ nombre: 'Suburban', marca: 'Chevrolet' },
{ nombre: 'Tahoe', marca: 'Chevrolet' },
{ nombre: 'Tigra', marca: 'Chevrolet' },
{ nombre: 'Tornado', marca: 'Chevrolet' },
{ nombre: 'Tracker', marca: 'Chevrolet' },
{ nombre: 'Trailblazer', marca: 'Chevrolet' },
{ nombre: 'Traverse', marca: 'Chevrolet' },
{ nombre: 'Van', marca: 'Chevrolet' },
{ nombre: 'Vectra', marca: 'Chevrolet' },
{ nombre: 'Veraneio', marca: 'Chevrolet' },
{ nombre: 'Volt', marca: 'Chevrolet' },
{ nombre: 'Zafira', marca: 'Chevrolet' },

// Modelos de Citroën - LISTA COMPLETA (36 modelos)
{ nombre: '11', marca: 'Citroën' },
{ nombre: '2Cv6', marca: 'Citroën' },
{ nombre: 'Ak 6', marca: 'Citroën' },
{ nombre: 'Ax', marca: 'Citroën' },
{ nombre: 'Azam', marca: 'Citroën' },
{ nombre: 'Basalt', marca: 'Citroën' },
{ nombre: 'Berlingo', marca: 'Citroën' },
{ nombre: 'Berlingo Multispace', marca: 'Citroën' },
{ nombre: 'Bx', marca: 'Citroën' },
{ nombre: 'C-Elysee', marca: 'Citroën' },
{ nombre: 'C1', marca: 'Citroën' },
{ nombre: 'C15', marca: 'Citroën' },
{ nombre: 'C2', marca: 'Citroën' },
{ nombre: 'C3', marca: 'Citroën' },
{ nombre: 'C3 Aircross', marca: 'Citroën' },
{ nombre: 'C3 Picasso', marca: 'Citroën' },
{ nombre: 'C4', marca: 'Citroën' },
{ nombre: 'C4 Cactus', marca: 'Citroën' },
{ nombre: 'C4 Picasso', marca: 'Citroën' },
{ nombre: 'C5', marca: 'Citroën' },
{ nombre: 'C5 Aircross', marca: 'Citroën' },
{ nombre: 'Ds3', marca: 'Citroën' },
{ nombre: 'Ds4', marca: 'Citroën' },
{ nombre: 'Ds5', marca: 'Citroën' },
{ nombre: 'Grand C4 Picasso', marca: 'Citroën' },
{ nombre: 'Gs', marca: 'Citroën' },
{ nombre: 'Jumper', marca: 'Citroën' },
{ nombre: 'Jumpy', marca: 'Citroën' },
{ nombre: 'Multispace', marca: 'Citroën' },
{ nombre: 'Nemo', marca: 'Citroën' },
{ nombre: 'Saxo', marca: 'Citroën' },
{ nombre: 'Spacetourer', marca: 'Citroën' },
{ nombre: 'Xsara', marca: 'Citroën' },
{ nombre: 'Xsara Picasso', marca: 'Citroën' },
{ nombre: 'Xsara2', marca: 'Citroën' },
{ nombre: 'Zx', marca: 'Citroën' },

// Modelos de Daewoo - LISTA COMPLETA (17 modelos)
{ nombre: 'A-85', marca: 'Daewoo' },
{ nombre: 'A100', marca: 'Daewoo' },
{ nombre: 'A110', marca: 'Daewoo' },
{ nombre: 'A90', marca: 'Daewoo' },
{ nombre: 'Damas', marca: 'Daewoo' },
{ nombre: 'Espero', marca: 'Daewoo' },
{ nombre: 'G 20E', marca: 'Daewoo' },
{ nombre: 'Heaven', marca: 'Daewoo' },
{ nombre: 'Korando', marca: 'Daewoo' },
{ nombre: 'Lanos', marca: 'Daewoo' },
{ nombre: 'Lestar', marca: 'Daewoo' },
{ nombre: 'Matiz', marca: 'Daewoo' },
{ nombre: 'Nubira', marca: 'Daewoo' },
{ nombre: 'Pointer', marca: 'Daewoo' },
{ nombre: 'Racer', marca: 'Daewoo' },
{ nombre: 'Super Salon', marca: 'Daewoo' },
{ nombre: 'Tico', marca: 'Daewoo' },

// Modelos de Daihatsu - LISTA COMPLETA (10 modelos)
{ nombre: 'Applause', marca: 'Daihatsu' },
{ nombre: 'Charade', marca: 'Daihatsu' },
{ nombre: 'Cuore', marca: 'Daihatsu' },
{ nombre: 'Delta', marca: 'Daihatsu' },
{ nombre: 'Feroza', marca: 'Daihatsu' },
{ nombre: 'Giro', marca: 'Daihatsu' },
{ nombre: 'Gran Move', marca: 'Daihatsu' },
{ nombre: 'Rocky', marca: 'Daihatsu' },
{ nombre: 'Taft', marca: 'Daihatsu' },
{ nombre: 'Terios', marca: 'Daihatsu' },

// Modelos de Dodge - LISTA COMPLETA (21 modelos)
{ nombre: '500', marca: 'Dodge' },
{ nombre: 'Aspen', marca: 'Dodge' },
{ nombre: 'Caliber', marca: 'Dodge' },
{ nombre: 'Caravan', marca: 'Dodge' },
{ nombre: 'Challenger', marca: 'Dodge' },
{ nombre: 'Charger', marca: 'Dodge' },
{ nombre: 'Coronet', marca: 'Dodge' },
{ nombre: 'Dakota', marca: 'Dodge' },
{ nombre: 'Dart', marca: 'Dodge' },
{ nombre: 'Dodge Ram', marca: 'Dodge' },
{ nombre: 'Durango', marca: 'Dodge' },
{ nombre: 'E300', marca: 'Dodge' },
{ nombre: 'Grand Caravan', marca: 'Dodge' },
{ nombre: 'Journey', marca: 'Dodge' },
{ nombre: 'Nitro', marca: 'Dodge' },
{ nombre: 'Polara', marca: 'Dodge' },
{ nombre: 'Ram 1500', marca: 'Dodge' },
{ nombre: 'Ram 2500', marca: 'Dodge' },
{ nombre: 'Ram 700', marca: 'Dodge' },
{ nombre: 'Sprinter', marca: 'Dodge' },
{ nombre: 'Viper', marca: 'Dodge' },

// Modelos de Ferrari - LISTA COMPLETA (13 modelos)
{ nombre: '296', marca: 'Ferrari' },
{ nombre: '296 GTS', marca: 'Ferrari' },
{ nombre: '348', marca: 'Ferrari' },
{ nombre: '456', marca: 'Ferrari' },
{ nombre: '458', marca: 'Ferrari' },
{ nombre: '458 Italia', marca: 'Ferrari' },
{ nombre: '488', marca: 'Ferrari' },
{ nombre: '812', marca: 'Ferrari' },
{ nombre: '812 GTS', marca: 'Ferrari' },
{ nombre: 'California', marca: 'Ferrari' },
{ nombre: 'F8 Tributo', marca: 'Ferrari' },
{ nombre: 'Roma', marca: 'Ferrari' },
{ nombre: 'Sf90', marca: 'Ferrari' },


// Modelos de Ford - LISTA COMPLETA (59 modelos)
{ nombre: '350', marca: 'Ford' },
{ nombre: 'A', marca: 'Ford' },
{ nombre: 'Aerostar', marca: 'Ford' },
{ nombre: 'Anglia', marca: 'Ford' },
{ nombre: 'Bronco', marca: 'Ford' },
{ nombre: 'Bronco Sport', marca: 'Ford' },
{ nombre: 'C-Max', marca: 'Ford' },
{ nombre: 'Cargo', marca: 'Ford' },
{ nombre: 'Crown Victoria', marca: 'Ford' },
{ nombre: 'E-350', marca: 'Ford' },
{ nombre: 'E450', marca: 'Ford' },
{ nombre: 'Econoline', marca: 'Ford' },
{ nombre: 'Ecosport', marca: 'Ford' },
{ nombre: 'Edge', marca: 'Ford' },
{ nombre: 'Edge St', marca: 'Ford' },
{ nombre: 'Escape', marca: 'Ford' },
{ nombre: 'Escort', marca: 'Ford' },
{ nombre: 'Euroescort', marca: 'Ford' },
{ nombre: 'Expedition', marca: 'Ford' },
{ nombre: 'Explorer', marca: 'Ford' },
{ nombre: 'Explorer Limited', marca: 'Ford' },
{ nombre: 'Explorer Sport Trac', marca: 'Ford' },
{ nombre: 'Explorer St', marca: 'Ford' },
{ nombre: 'F-100', marca: 'Ford' },
{ nombre: 'F-150', marca: 'Ford' },
{ nombre: 'F-150 3.5', marca: 'Ford' },
{ nombre: 'F-150 Raptor', marca: 'Ford' },
{ nombre: 'F-150 Xlt 5.4 4Wd', marca: 'Ford' },
{ nombre: 'F-250', marca: 'Ford' },
{ nombre: 'F-350', marca: 'Ford' },
{ nombre: 'F-4000', marca: 'Ford' },
{ nombre: 'Fairlaine', marca: 'Ford' },
{ nombre: 'Falcon', marca: 'Ford' },
{ nombre: 'Fiesta', marca: 'Ford' },
{ nombre: 'Fiesta Hb', marca: 'Ford' },
{ nombre: 'Focus', marca: 'Ford' },
{ nombre: 'Fusion', marca: 'Ford' },
{ nombre: 'Fusion 2.0', marca: 'Ford' },
{ nombre: 'Galaxie', marca: 'Ford' },
{ nombre: 'Ka', marca: 'Ford' },
{ nombre: 'Ltd', marca: 'Ford' },
{ nombre: 'Maverick', marca: 'Ford' },
{ nombre: 'Mondeo', marca: 'Ford' },
{ nombre: 'Mustang', marca: 'Ford' },
{ nombre: 'Probe', marca: 'Ford' },
{ nombre: 'Ranger', marca: 'Ford' },
{ nombre: 'Ranger Heritage', marca: 'Ford' },
{ nombre: 'Ranger Raptor', marca: 'Ford' },
{ nombre: 'Raptor', marca: 'Ford' },
{ nombre: 'Taunus', marca: 'Ford' },
{ nombre: 'Taurus', marca: 'Ford' },
{ nombre: 'Territory', marca: 'Ford' },
{ nombre: 'Thunderbird', marca: 'Ford' },
{ nombre: 'Torino', marca: 'Ford' },
{ nombre: 'Transit', marca: 'Ford' },
{ nombre: 'Transit Custom', marca: 'Ford' },
{ nombre: 'Tudor', marca: 'Ford' },
{ nombre: 'V8', marca: 'Ford' },
{ nombre: 'Windstar', marca: 'Ford' },

// Modelos de Honda - LISTA COMPLETA (75+ modelos)
// Incluye autos, motos, ATVs y vehículos recreativos

// === AUTOS ===
{ nombre: 'Accord', marca: 'Honda' },
{ nombre: 'Civic', marca: 'Honda' },
{ nombre: 'City', marca: 'Honda' },
{ nombre: 'Cr-V', marca: 'Honda' },
{ nombre: 'Hr-V', marca: 'Honda' },
{ nombre: 'Fit', marca: 'Honda' },
{ nombre: 'Jazz', marca: 'Honda' },
{ nombre: 'Pilot', marca: 'Honda' },
{ nombre: 'Ridgeline', marca: 'Honda' },
{ nombre: 'Passport', marca: 'Honda' },
{ nombre: 'Odyssey', marca: 'Honda' },
{ nombre: 'Insight', marca: 'Honda' },
{ nombre: 'Clarity', marca: 'Honda' },
{ nombre: 'Element', marca: 'Honda' },
{ nombre: 'S2000', marca: 'Honda' },
{ nombre: 'NSX', marca: 'Honda' },
{ nombre: 'Prelude', marca: 'Honda' },
{ nombre: 'Integra', marca: 'Honda' },
{ nombre: 'Legend', marca: 'Honda' },
{ nombre: 'Stream', marca: 'Honda' },
{ nombre: 'Freed', marca: 'Honda' },
{ nombre: 'Stepwgn', marca: 'Honda' },
{ nombre: 'Vezel', marca: 'Honda' },
{ nombre: 'Shuttle', marca: 'Honda' },
{ nombre: 'Grace', marca: 'Honda' },
{ nombre: 'Wr-V', marca: 'Honda' },
{ nombre: 'Zr-V', marca: 'Honda' },
{ nombre: 'Cr-Z', marca: 'Honda' },
{ nombre: 'Del Sol', marca: 'Honda' },
{ nombre: 'Beat', marca: 'Honda' },

// === MOTOS - DEPORTIVAS ===
{ nombre: 'CBR125R', marca: 'Honda' },
{ nombre: 'CBR250R', marca: 'Honda' },
{ nombre: 'CBR300R', marca: 'Honda' },
{ nombre: 'CBR400R', marca: 'Honda' },
{ nombre: 'CBR500R', marca: 'Honda' },
{ nombre: 'CBR600F', marca: 'Honda' },
{ nombre: 'CBR600RR', marca: 'Honda' },
{ nombre: 'CBR650R', marca: 'Honda' },
{ nombre: 'CBR900RR', marca: 'Honda' },
{ nombre: 'CBR1000RR', marca: 'Honda' },
{ nombre: 'CBR1100XX', marca: 'Honda' },
{ nombre: 'VFR800', marca: 'Honda' },
{ nombre: 'VFR1200', marca: 'Honda' },
{ nombre: 'RC213V-S', marca: 'Honda' },

// === MOTOS - NAKED/STREET ===
{ nombre: 'CB125F', marca: 'Honda' },
{ nombre: 'CB125R', marca: 'Honda' },
{ nombre: 'CB190R', marca: 'Honda' },
{ nombre: 'CB250F', marca: 'Honda' },
{ nombre: 'CB300F', marca: 'Honda' },
{ nombre: 'CB300R', marca: 'Honda' },
{ nombre: 'CB400', marca: 'Honda' },
{ nombre: 'CB500F', marca: 'Honda' },
{ nombre: 'CB600F', marca: 'Honda' },
{ nombre: 'CB650F', marca: 'Honda' },
{ nombre: 'CB650R', marca: 'Honda' },
{ nombre: 'CB750', marca: 'Honda' },
{ nombre: 'CB900', marca: 'Honda' },
{ nombre: 'CB1000R', marca: 'Honda' },
{ nombre: 'CB1100', marca: 'Honda' },
{ nombre: 'CB1300', marca: 'Honda' },
{ nombre: 'Hornet 600', marca: 'Honda' },
{ nombre: 'Hornet 900', marca: 'Honda' },

// === MOTOS - CRUISER ===
{ nombre: 'Shadow 125', marca: 'Honda' },
{ nombre: 'Shadow 400', marca: 'Honda' },
{ nombre: 'Shadow 600', marca: 'Honda' },
{ nombre: 'Shadow 750', marca: 'Honda' },
{ nombre: 'Shadow 1100', marca: 'Honda' },
{ nombre: 'Fury', marca: 'Honda' },
{ nombre: 'Stateline', marca: 'Honda' },
{ nombre: 'Interstate', marca: 'Honda' },
{ nombre: 'Sabre', marca: 'Honda' },

// === MOTOS - TOURING ===
{ nombre: 'Gold Wing', marca: 'Honda' },
{ nombre: 'ST1100', marca: 'Honda' },
{ nombre: 'ST1300', marca: 'Honda' },
{ nombre: 'CTX700', marca: 'Honda' },
{ nombre: 'CTX1300', marca: 'Honda' },
{ nombre: 'NT700V', marca: 'Honda' },

// === MOTOS - ADVENTURE/DUAL SPORT ===
{ nombre: 'Africa Twin', marca: 'Honda' },
{ nombre: 'CRF250L', marca: 'Honda' },
{ nombre: 'CRF250Rally', marca: 'Honda' },
{ nombre: 'CRF450L', marca: 'Honda' },
{ nombre: 'CRF1000L', marca: 'Honda' },
{ nombre: 'CRF1100L', marca: 'Honda' },
{ nombre: 'XL700V', marca: 'Honda' },
{ nombre: 'NC700X', marca: 'Honda' },
{ nombre: 'NC750X', marca: 'Honda' },
{ nombre: 'XR650L', marca: 'Honda' },

// === MOTOS - SCOOTER ===
{ nombre: 'PCX125', marca: 'Honda' },
{ nombre: 'PCX150', marca: 'Honda' },
{ nombre: 'SH125i', marca: 'Honda' },
{ nombre: 'SH150i', marca: 'Honda' },
{ nombre: 'SH300i', marca: 'Honda' },
{ nombre: 'Forza 125', marca: 'Honda' },
{ nombre: 'Forza 300', marca: 'Honda' },
{ nombre: 'Forza 750', marca: 'Honda' },
{ nombre: 'Silver Wing', marca: 'Honda' },

// === MOTOS - DIRT BIKE/MOTOCROSS ===
{ nombre: 'CRF50F', marca: 'Honda' },
{ nombre: 'CRF110F', marca: 'Honda' },
{ nombre: 'CRF125F', marca: 'Honda' },
{ nombre: 'CRF150R', marca: 'Honda' },
{ nombre: 'CRF230F', marca: 'Honda' },
{ nombre: 'CRF250R', marca: 'Honda' },
{ nombre: 'CRF250X', marca: 'Honda' },
{ nombre: 'CRF450R', marca: 'Honda' },
{ nombre: 'CRF450X', marca: 'Honda' },

// === ATVs Y VEHÍCULOS RECREATIVOS ===
{ nombre: 'TRX90X', marca: 'Honda' },
{ nombre: 'TRX250X', marca: 'Honda' },
{ nombre: 'TRX400X', marca: 'Honda' },
{ nombre: 'TRX450R', marca: 'Honda' },
{ nombre: 'TRX700XX', marca: 'Honda' },
{ nombre: 'FourTrax', marca: 'Honda' },
{ nombre: 'Rancher', marca: 'Honda' },
{ nombre: 'Foreman', marca: 'Honda' },
{ nombre: 'Rubicon', marca: 'Honda' },
{ nombre: 'Pioneer 500', marca: 'Honda' },
{ nombre: 'Pioneer 700', marca: 'Honda' },
{ nombre: 'Pioneer 1000', marca: 'Honda' },
{ nombre: 'Talon 1000X', marca: 'Honda' },
{ nombre: 'Talon 1000R', marca: 'Honda' },

// === VEHÍCULOS ACUÁTICOS ===
{ nombre: 'Aquatrax F-12', marca: 'Honda' },
{ nombre: 'Aquatrax F-12X', marca: 'Honda' },
{ nombre: 'Aquatrax F-15X', marca: 'Honda' },
{ nombre: 'Aquatrax R-12', marca: 'Honda' },
{ nombre: 'Aquatrax R-12X', marca: 'Honda' },

// Modelos de Hyundai - LISTA COMPLETA (54 modelos)
{ nombre: 'Accent', marca: 'Hyundai' },
{ nombre: 'Accent Prime', marca: 'Hyundai' },
{ nombre: 'Atos', marca: 'Hyundai' },
{ nombre: 'Avante', marca: 'Hyundai' },
{ nombre: 'Azera', marca: 'Hyundai' },
{ nombre: 'Coupe', marca: 'Hyundai' },
{ nombre: 'Creta', marca: 'Hyundai' },
{ nombre: 'Creta Grand', marca: 'Hyundai' },
{ nombre: 'Elantra', marca: 'Hyundai' },
{ nombre: 'Eon', marca: 'Hyundai' },
{ nombre: 'Equus', marca: 'Hyundai' },
{ nombre: 'Excel', marca: 'Hyundai' },
{ nombre: 'Galloper', marca: 'Hyundai' },
{ nombre: 'Galloper II', marca: 'Hyundai' },
{ nombre: 'Genesis', marca: 'Hyundai' },
{ nombre: 'Getz', marca: 'Hyundai' },
{ nombre: 'Grace', marca: 'Hyundai' },
{ nombre: 'Grand I10', marca: 'Hyundai' },
{ nombre: 'Grand Santa Fe', marca: 'Hyundai' },
{ nombre: 'H-1', marca: 'Hyundai' },
{ nombre: 'H-100', marca: 'Hyundai' },
{ nombre: 'H350', marca: 'Hyundai' },
{ nombre: 'H350 Solati', marca: 'Hyundai' },
{ nombre: 'Hd35', marca: 'Hyundai' },
{ nombre: 'Hd65', marca: 'Hyundai' },
{ nombre: 'I10', marca: 'Hyundai' },
{ nombre: 'I20', marca: 'Hyundai' },
{ nombre: 'I30', marca: 'Hyundai' },
{ nombre: 'I40', marca: 'Hyundai' },
{ nombre: 'Ioniq', marca: 'Hyundai' },
{ nombre: 'Kona', marca: 'Hyundai' },
{ nombre: 'Matrix', marca: 'Hyundai' },
{ nombre: 'New H1', marca: 'Hyundai' },
{ nombre: 'New Tucson', marca: 'Hyundai' },
{ nombre: 'Palisade', marca: 'Hyundai' },
{ nombre: 'Porter', marca: 'Hyundai' },
{ nombre: 'Porter Hr', marca: 'Hyundai' },
{ nombre: 'Porter II', marca: 'Hyundai' },
{ nombre: 'Santa Fe', marca: 'Hyundai' },
{ nombre: 'Santamo', marca: 'Hyundai' },
{ nombre: 'Sonata', marca: 'Hyundai' },
{ nombre: 'Starex', marca: 'Hyundai' },
{ nombre: 'Staria', marca: 'Hyundai' },
{ nombre: 'Terracan', marca: 'Hyundai' },
{ nombre: 'Tiburon', marca: 'Hyundai' },
{ nombre: 'Trajet', marca: 'Hyundai' },
{ nombre: 'Tucson', marca: 'Hyundai' },
{ nombre: 'Tuscani', marca: 'Hyundai' },
{ nombre: 'Veloster', marca: 'Hyundai' },
{ nombre: 'Venue', marca: 'Hyundai' },
{ nombre: 'Venue Qx', marca: 'Hyundai' },
{ nombre: 'Veracruz', marca: 'Hyundai' },
{ nombre: 'Verna', marca: 'Hyundai' },
{ nombre: 'Xg', marca: 'Hyundai' },

// Modelos de Jaguar - LISTA COMPLETA (16 modelos)
{ nombre: 'E-Pace', marca: 'Jaguar' },
{ nombre: 'F-Pace', marca: 'Jaguar' },
{ nombre: 'F-Type', marca: 'Jaguar' },
{ nombre: 'I-Pace', marca: 'Jaguar' },
{ nombre: 'Mk', marca: 'Jaguar' },
{ nombre: 'Mk2', marca: 'Jaguar' },
{ nombre: 'S-Type', marca: 'Jaguar' },
{ nombre: 'XE', marca: 'Jaguar' },
{ nombre: 'XF', marca: 'Jaguar' },
{ nombre: 'XJ', marca: 'Jaguar' },
{ nombre: 'XJ12', marca: 'Jaguar' },
{ nombre: 'XJ6', marca: 'Jaguar' },
{ nombre: 'XJ8', marca: 'Jaguar' },
{ nombre: 'XK', marca: 'Jaguar' },
{ nombre: 'XKR', marca: 'Jaguar' },
{ nombre: 'X-Type', marca: 'Jaguar' },

// Modelos de Jeep - LISTA COMPLETA (13 modelos)
{ nombre: 'Cherokee', marca: 'Jeep' },
{ nombre: 'Cj7', marca: 'Jeep' },
{ nombre: 'Commander', marca: 'Jeep' },
{ nombre: 'Compass', marca: 'Jeep' },
{ nombre: 'Gladiator', marca: 'Jeep' },
{ nombre: 'Grand Cherokee', marca: 'Jeep' },
{ nombre: 'Liberty', marca: 'Jeep' },
{ nombre: 'New Cherokee', marca: 'Jeep' },
{ nombre: 'New Grand Cherokee', marca: 'Jeep' },
{ nombre: 'Patriot', marca: 'Jeep' },
{ nombre: 'Renegade', marca: 'Jeep' },
{ nombre: 'Willys', marca: 'Jeep' },
{ nombre: 'Wrangler', marca: 'Jeep' },

// Modelos de Kia - LISTA COMPLETA (41 modelos)
{ nombre: 'Avella', marca: 'Kia' },
{ nombre: 'Avella II', marca: 'Kia' },
{ nombre: 'Besta', marca: 'Kia' },
{ nombre: 'Besta II', marca: 'Kia' },
{ nombre: 'Cadenza', marca: 'Kia' },
{ nombre: 'Carens', marca: 'Kia' },
{ nombre: 'Carnival', marca: 'Kia' },
{ nombre: 'Cerato', marca: 'Kia' },
{ nombre: 'Cerato 5', marca: 'Kia' },
{ nombre: 'Frontier', marca: 'Kia' },
{ nombre: 'Frontier II', marca: 'Kia' },
{ nombre: 'Grand Carnival', marca: 'Kia' },
{ nombre: 'K3', marca: 'Kia' },
{ nombre: 'K3 Cross', marca: 'Kia' },
{ nombre: 'Koup', marca: 'Kia' },
{ nombre: 'Magentis', marca: 'Kia' },
{ nombre: 'Mohave', marca: 'Kia' },
{ nombre: 'Morning', marca: 'Kia' },
{ nombre: 'Niro', marca: 'Kia' },
{ nombre: 'Opirus', marca: 'Kia' },
{ nombre: 'Optima', marca: 'Kia' },
{ nombre: 'Pop', marca: 'Kia' },
{ nombre: 'Pride', marca: 'Kia' },
{ nombre: 'Quoris', marca: 'Kia' },
{ nombre: 'Rio', marca: 'Kia' },
{ nombre: 'Rio 3', marca: 'Kia' },
{ nombre: 'Rio 4', marca: 'Kia' },
{ nombre: 'Rio 5', marca: 'Kia' },
{ nombre: 'Rio II', marca: 'Kia' },
{ nombre: 'Rio Jb', marca: 'Kia' },
{ nombre: 'Scoupe', marca: 'Kia' },
{ nombre: 'Seltos', marca: 'Kia' },
{ nombre: 'Sephia', marca: 'Kia' },
{ nombre: 'Soluto', marca: 'Kia' },
{ nombre: 'Sonet', marca: 'Kia' },
{ nombre: 'Sorento', marca: 'Kia' },
{ nombre: 'Soul', marca: 'Kia' },
{ nombre: 'Spectra', marca: 'Kia' },
{ nombre: 'Sportage', marca: 'Kia' },
{ nombre: 'Sportage Pro', marca: 'Kia' },
{ nombre: 'Stinger', marca: 'Kia' },


// Modelos de Land Rover - LISTA COMPLETA (11 modelos)
{ nombre: 'Corto', marca: 'Land Rover' },
{ nombre: 'Defender', marca: 'Land Rover' },
{ nombre: 'Discovery', marca: 'Land Rover' },
{ nombre: 'Discovery Sport', marca: 'Land Rover' },
{ nombre: 'Evoque', marca: 'Land Rover' },
{ nombre: 'Freelander', marca: 'Land Rover' },
{ nombre: 'Freelander 2', marca: 'Land Rover' },
{ nombre: 'Range Rover', marca: 'Land Rover' },
{ nombre: 'Range Rover Evoque', marca: 'Land Rover' },
{ nombre: 'Range Rover Sport', marca: 'Land Rover' },
{ nombre: 'Range Rover Velar', marca: 'Land Rover' },

// Modelos de Mahindra - LISTA COMPLETA (8 modelos)
{ nombre: 'Genio', marca: 'Mahindra' },
{ nombre: 'Kuv100', marca: 'Mahindra' },
{ nombre: 'New Scorpio', marca: 'Mahindra' },
{ nombre: 'Pick Up', marca: 'Mahindra' },
{ nombre: 'Quanto', marca: 'Mahindra' },
{ nombre: 'Scorpio', marca: 'Mahindra' },
{ nombre: 'Xuv300', marca: 'Mahindra' },
{ nombre: 'Xuv500', marca: 'Mahindra' },

// Modelos de Mazda - LISTA COMPLETA (25 modelos)
{ nombre: '2', marca: 'Mazda' },
{ nombre: '3', marca: 'Mazda' },
{ nombre: '3 Sport', marca: 'Mazda' },
{ nombre: '5', marca: 'Mazda' },
{ nombre: '6', marca: 'Mazda' },
{ nombre: '626', marca: 'Mazda' },
{ nombre: 'B-2200', marca: 'Mazda' },
{ nombre: 'B-2500', marca: 'Mazda' },
{ nombre: 'Bt-50', marca: 'Mazda' },
{ nombre: 'Cx-3', marca: 'Mazda' },
{ nombre: 'Cx-30', marca: 'Mazda' },
{ nombre: 'Cx-5', marca: 'Mazda' },
{ nombre: 'Cx-7', marca: 'Mazda' },
{ nombre: 'Cx-9', marca: 'Mazda' },
{ nombre: 'Demio', marca: 'Mazda' },
{ nombre: 'Millenia', marca: 'Mazda' },
{ nombre: 'Mpv', marca: 'Mazda' },
{ nombre: 'Mx-3', marca: 'Mazda' },
{ nombre: 'Mx-5', marca: 'Mazda' },
{ nombre: 'Mx-6', marca: 'Mazda' },
{ nombre: 'Premacy', marca: 'Mazda' },
{ nombre: 'Protege', marca: 'Mazda' },
{ nombre: 'Rx-7', marca: 'Mazda' },
{ nombre: 'Rx-8', marca: 'Mazda' },
{ nombre: 'Tribute', marca: 'Mazda' },

// === MODELOS CON NÚMEROS ===
{ nombre: '113', marca: 'Mercedes-Benz' },
{ nombre: '180', marca: 'Mercedes-Benz' },
{ nombre: '190', marca: 'Mercedes-Benz' },
{ nombre: '200', marca: 'Mercedes-Benz' },
{ nombre: '220', marca: 'Mercedes-Benz' },
{ nombre: '230', marca: 'Mercedes-Benz' },
{ nombre: '240', marca: 'Mercedes-Benz' },
{ nombre: '250', marca: 'Mercedes-Benz' },
{ nombre: '260', marca: 'Mercedes-Benz' },
{ nombre: '280', marca: 'Mercedes-Benz' },
{ nombre: '280 C', marca: 'Mercedes-Benz' },
{ nombre: '280 Sl', marca: 'Mercedes-Benz' },
{ nombre: '300', marca: 'Mercedes-Benz' },
{ nombre: '300 Ce', marca: 'Mercedes-Benz' },
{ nombre: '300 E', marca: 'Mercedes-Benz' },
{ nombre: '300 SE', marca: 'Mercedes-Benz' },
{ nombre: '320 E', marca: 'Mercedes-Benz' },
{ nombre: '350', marca: 'Mercedes-Benz' },
{ nombre: '380', marca: 'Mercedes-Benz' },
{ nombre: '450 Sl', marca: 'Mercedes-Benz' },
{ nombre: '500', marca: 'Mercedes-Benz' },

// === SERIE A ===
{ nombre: 'A 180', marca: 'Mercedes-Benz' },
{ nombre: 'A 200', marca: 'Mercedes-Benz' },
{ nombre: 'A 250', marca: 'Mercedes-Benz' },
{ nombre: 'A 35 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'A 45 Amg', marca: 'Mercedes-Benz' },

// === SERIE B ===
{ nombre: 'B 180', marca: 'Mercedes-Benz' },
{ nombre: 'B 200', marca: 'Mercedes-Benz' },
{ nombre: 'B 220', marca: 'Mercedes-Benz' },

// === SERIE C ===
{ nombre: 'C 180', marca: 'Mercedes-Benz' },
{ nombre: 'C 200', marca: 'Mercedes-Benz' },
{ nombre: 'C 220', marca: 'Mercedes-Benz' },
{ nombre: 'C 230', marca: 'Mercedes-Benz' },
{ nombre: 'C 240', marca: 'Mercedes-Benz' },
{ nombre: 'C 250', marca: 'Mercedes-Benz' },
{ nombre: 'C 280', marca: 'Mercedes-Benz' },
{ nombre: 'C 300', marca: 'Mercedes-Benz' },
{ nombre: 'C 300 Coupe', marca: 'Mercedes-Benz' },
{ nombre: 'C 320', marca: 'Mercedes-Benz' },
{ nombre: 'C 350', marca: 'Mercedes-Benz' },
{ nombre: 'C 43 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'C 450', marca: 'Mercedes-Benz' },
{ nombre: 'C 55 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'C 63', marca: 'Mercedes-Benz' },
{ nombre: 'C 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'C32 AMG', marca: 'Mercedes-Benz' },

// === SERIE E ===
{ nombre: 'E 190', marca: 'Mercedes-Benz' },
{ nombre: 'E 200', marca: 'Mercedes-Benz' },
{ nombre: 'E 220', marca: 'Mercedes-Benz' },
{ nombre: 'E 220 D', marca: 'Mercedes-Benz' },
{ nombre: 'E 240', marca: 'Mercedes-Benz' },
{ nombre: 'E 250', marca: 'Mercedes-Benz' },
{ nombre: 'E 280', marca: 'Mercedes-Benz' },
{ nombre: 'E 300', marca: 'Mercedes-Benz' },
{ nombre: 'E 320', marca: 'Mercedes-Benz' },
{ nombre: 'E 350', marca: 'Mercedes-Benz' },
{ nombre: 'E 400', marca: 'Mercedes-Benz' },
{ nombre: 'E 43 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'E 450', marca: 'Mercedes-Benz' },
{ nombre: 'E 500', marca: 'Mercedes-Benz' },
{ nombre: 'E 55 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'E 63', marca: 'Mercedes-Benz' },
{ nombre: 'E 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'E 63S Amg', marca: 'Mercedes-Benz' },
{ nombre: 'E53 Amg', marca: 'Mercedes-Benz' },

// === SERIE S ===
{ nombre: 'S 320', marca: 'Mercedes-Benz' },
{ nombre: 'S 350', marca: 'Mercedes-Benz' },
{ nombre: 'S 400', marca: 'Mercedes-Benz' },
{ nombre: 'S 420', marca: 'Mercedes-Benz' },
{ nombre: 'S 430', marca: 'Mercedes-Benz' },
{ nombre: 'S 500', marca: 'Mercedes-Benz' },
{ nombre: 'S 550', marca: 'Mercedes-Benz' },
{ nombre: 'S 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'S600l', marca: 'Mercedes-Benz' },

// === SERIE G (SUV) ===
{ nombre: 'G', marca: 'Mercedes-Benz' },
{ nombre: 'G 280', marca: 'Mercedes-Benz' },
{ nombre: 'G 350', marca: 'Mercedes-Benz' },
{ nombre: 'G 500', marca: 'Mercedes-Benz' },
{ nombre: 'G 63 Amg', marca: 'Mercedes-Benz' },

// === SERIE GL/GLS ===
{ nombre: 'Gl 320', marca: 'Mercedes-Benz' },
{ nombre: 'Gl 350', marca: 'Mercedes-Benz' },
{ nombre: 'Gl 450', marca: 'Mercedes-Benz' },
{ nombre: 'Gl 500', marca: 'Mercedes-Benz' },
{ nombre: 'Gl 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gls', marca: 'Mercedes-Benz' },
{ nombre: 'Gls 350', marca: 'Mercedes-Benz' },
{ nombre: 'GLS 400', marca: 'Mercedes-Benz' },
{ nombre: 'Gls 500', marca: 'Mercedes-Benz' },

// === SERIE GLA ===
{ nombre: 'Gla', marca: 'Mercedes-Benz' },
{ nombre: 'Gla 200', marca: 'Mercedes-Benz' },
{ nombre: 'Gla 220', marca: 'Mercedes-Benz' },
{ nombre: 'Gla 220D', marca: 'Mercedes-Benz' },
{ nombre: 'Gla 250', marca: 'Mercedes-Benz' },
{ nombre: 'Gla 45 Amg', marca: 'Mercedes-Benz' },

// === SERIE GLB ===
{ nombre: 'Glb', marca: 'Mercedes-Benz' },
{ nombre: 'GLB 200', marca: 'Mercedes-Benz' },

// === SERIE GLC ===
{ nombre: 'Glc', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 200', marca: 'Mercedes-Benz' },
{ nombre: 'GLC 200 Coupe', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 220', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 250', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 300', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 350', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 43 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Glc 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Glc Coupe', marca: 'Mercedes-Benz' },

// === SERIE GLE ===
{ nombre: 'Gle', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 250', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 300 D', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 350', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 350D Coupe Sport', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 400', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 43 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 450', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 500', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 53 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 53 Amg Coupe', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 63 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gle 63 S Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe 350', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe 400', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe 43 Amg', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe 450', marca: 'Mercedes-Benz' },
{ nombre: 'Gle Coupe 63 Amg', marca: 'Mercedes-Benz' },

// === SERIE GLK ===
{ nombre: 'Glk 220', marca: 'Mercedes-Benz' },
{ nombre: 'Glk 350', marca: 'Mercedes-Benz' },

// === SERIE ML ===
{ nombre: 'Ml 250', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 270', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 300', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 320', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 350', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 400', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 430', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 500', marca: 'Mercedes-Benz' },
{ nombre: 'Ml 63 Amg', marca: 'Mercedes-Benz' },

// === SERIE CLA ===
{ nombre: 'Cla 180', marca: 'Mercedes-Benz' },
{ nombre: 'Cla 200', marca: 'Mercedes-Benz' },
{ nombre: 'Cla 220', marca: 'Mercedes-Benz' },
{ nombre: 'Cla 250', marca: 'Mercedes-Benz' },
{ nombre: 'Cla 45 Amg', marca: 'Mercedes-Benz' },

// === SERIE CLC ===
{ nombre: 'Clc 180', marca: 'Mercedes-Benz' },
{ nombre: 'Clc 200', marca: 'Mercedes-Benz' },

// === SERIE CLK ===
{ nombre: 'Clk 280', marca: 'Mercedes-Benz' },
{ nombre: 'Clk 320', marca: 'Mercedes-Benz' },
{ nombre: 'Clk 350', marca: 'Mercedes-Benz' },
{ nombre: 'Clk 500', marca: 'Mercedes-Benz' },

// === SERIE CLS ===
{ nombre: 'Cls 350', marca: 'Mercedes-Benz' },
{ nombre: 'Cls 400', marca: 'Mercedes-Benz' },
{ nombre: 'Cls 500', marca: 'Mercedes-Benz' },
{ nombre: 'Cls 63 Amg', marca: 'Mercedes-Benz' },

// === SERIE SL ===
{ nombre: 'Sl 320', marca: 'Mercedes-Benz' },
{ nombre: 'Sl 350', marca: 'Mercedes-Benz' },
{ nombre: 'Sl 400', marca: 'Mercedes-Benz' },
{ nombre: 'Sl 500', marca: 'Mercedes-Benz' },
{ nombre: 'Sl 55', marca: 'Mercedes-Benz' },

// === SERIE SLC ===
{ nombre: 'Slc 200', marca: 'Mercedes-Benz' },
{ nombre: 'Slc 300', marca: 'Mercedes-Benz' },
{ nombre: 'Slc 450', marca: 'Mercedes-Benz' },

// === SERIE SLK ===
{ nombre: 'Slk 200', marca: 'Mercedes-Benz' },
{ nombre: 'Slk 230', marca: 'Mercedes-Benz' },
{ nombre: 'Slk 280', marca: 'Mercedes-Benz' },
{ nombre: 'Slk 350', marca: 'Mercedes-Benz' },

// === COMERCIALES ===
{ nombre: 'Citan', marca: 'Mercedes-Benz' },
{ nombre: 'Citan 109', marca: 'Mercedes-Benz' },
{ nombre: 'Citan 111', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 213', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 308', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 313', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 315', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 316', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 413', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 415', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 416 CDI', marca: 'Mercedes-Benz' },
{ nombre: 'Sprinter 515', marca: 'Mercedes-Benz' },
{ nombre: 'sprinter 516 CDI', marca: 'Mercedes-Benz' },
{ nombre: 'V 220', marca: 'Mercedes-Benz' },
{ nombre: 'Viano', marca: 'Mercedes-Benz' },
{ nombre: 'Vito', marca: 'Mercedes-Benz' },
{ nombre: 'Vito 109', marca: 'Mercedes-Benz' },
{ nombre: 'Vito 110', marca: 'Mercedes-Benz' },
{ nombre: 'Vito 111', marca: 'Mercedes-Benz' },
{ nombre: 'Vito 113', marca: 'Mercedes-Benz' },
{ nombre: 'Vito 114', marca: 'Mercedes-Benz' },
{ nombre: 'Vito Tourer 114', marca: 'Mercedes-Benz' },
{ nombre: 'Vito Tourer 116 CDI', marca: 'Mercedes-Benz' },
{ nombre: 'Vito-110', marca: 'Mercedes-Benz' },
{ nombre: 'Vito111 CDI', marca: 'Mercedes-Benz' },

// === CLASE ESPECIALES ===
{ nombre: 'Clase G', marca: 'Mercedes-Benz' },
{ nombre: 'Clase V', marca: 'Mercedes-Benz' },
{ nombre: 'Clase X', marca: 'Mercedes-Benz' },

// === DEPORTIVOS/AMG/GT ===
{ nombre: 'Amg Gt', marca: 'Mercedes-Benz' },
{ nombre: 'GT63s', marca: 'Mercedes-Benz' },

// === ELÉCTRICOS ===
{ nombre: 'Eqa', marca: 'Mercedes-Benz' },
{ nombre: 'Eqe', marca: 'Mercedes-Benz' },

// === OTROS MODELOS ===
{ nombre: 'Cl 500', marca: 'Mercedes-Benz' },
{ nombre: 'R 350', marca: 'Mercedes-Benz' },
{ nombre: 'Se 300', marca: 'Mercedes-Benz' },
{ nombre: 'X 250D', marca: 'Mercedes-Benz' },
{ nombre: 'X350 D', marca: 'Mercedes-Benz' },

// === MODELOS CON NÚMEROS (CLÁSICOS) ===
{ nombre: '3', marca: 'MG' },
{ nombre: '5', marca: 'MG' },
{ nombre: '6', marca: 'MG' },
{ nombre: '7', marca: 'MG' },

// === MODELOS MODERNOS ===
{ nombre: 'MG3', marca: 'MG' },
{ nombre: 'MG5', marca: 'MG' },
{ nombre: 'MG6', marca: 'MG' },
{ nombre: 'MG7', marca: 'MG' },
{ nombre: 'MG ZS', marca: 'MG' },
{ nombre: 'MG ZS EV', marca: 'MG' },
{ nombre: 'MG HS', marca: 'MG' },
{ nombre: 'MG RX5', marca: 'MG' },
{ nombre: 'MG RX8', marca: 'MG' },
{ nombre: 'MG GT', marca: 'MG' },
{ nombre: 'MG GS', marca: 'MG' },

// === MODELOS CLÁSICOS/HISTÓRICOS ===
{ nombre: 'MGA', marca: 'MG' },
{ nombre: 'MGB', marca: 'MG' },
{ nombre: 'MGB GT', marca: 'MG' },
{ nombre: 'MGC', marca: 'MG' },
{ nombre: 'Midget', marca: 'MG' },
{ nombre: 'TF', marca: 'MG' },
{ nombre: 'TD', marca: 'MG' },
{ nombre: 'TC', marca: 'MG' },
{ nombre: 'TA', marca: 'MG' },
{ nombre: 'TB', marca: 'MG' },

// === MODELOS ESPECIALES ===
{ nombre: 'ZR', marca: 'MG' },
{ nombre: 'ZT', marca: 'MG' },
{ nombre: 'ZT-T', marca: 'MG' },
{ nombre: 'F', marca: 'MG' },

// === MODELOS QUE COMIENZAN CON NÚMEROS/LETRAS ===
{ nombre: 'L200', marca: 'Mitsubishi' },
{ nombre: 'L300', marca: 'Mitsubishi' },

// === SUVs/CROSSOVERS ===
{ nombre: 'Asx', marca: 'Mitsubishi' },
{ nombre: 'Eclipse Cross', marca: 'Mitsubishi' },
{ nombre: 'Montero', marca: 'Mitsubishi' },
{ nombre: 'Montero Sport', marca: 'Mitsubishi' },
{ nombre: 'Outlander', marca: 'Mitsubishi' },
{ nombre: 'Outlander Sport', marca: 'Mitsubishi' },
{ nombre: 'Rvr', marca: 'Mitsubishi' },
{ nombre: 'Xpander', marca: 'Mitsubishi' },
{ nombre: 'Xpander Cross', marca: 'Mitsubishi' },

// === SEDANES/HATCHBACKS ===
{ nombre: 'Colt', marca: 'Mitsubishi' },
{ nombre: 'Galant', marca: 'Mitsubishi' },
{ nombre: 'Lancer', marca: 'Mitsubishi' },
{ nombre: 'Mirage', marca: 'Mitsubishi' },

// === DEPORTIVOS ===
{ nombre: 'Eclipse', marca: 'Mitsubishi' },
{ nombre: 'Evo', marca: 'Mitsubishi' },
{ nombre: 'Gt 3000', marca: 'Mitsubishi' },

// === COMERCIALES/ESPECIALES ===
{ nombre: 'Delica', marca: 'Mitsubishi' },
{ nombre: 'Katana', marca: 'Mitsubishi' },


// Modelos de Nissan - LISTA COMPLETA (50 modelos)
// Incluye modelos que comienzan con números como solicitado

// === MODELOS QUE COMIENZAN CON NÚMEROS ===
{ nombre: '200sx', marca: 'Nissan' },
{ nombre: '240sx', marca: 'Nissan' },
{ nombre: '300zx', marca: 'Nissan' },
{ nombre: '350z', marca: 'Nissan' },
{ nombre: '370z', marca: 'Nissan' },

// === MODELOS OBSERVADOS EN EL SCRAPING ===
{ nombre: 'Kicks', marca: 'Nissan' },
{ nombre: 'March', marca: 'Nissan' },
{ nombre: 'Navara', marca: 'Nissan' },
{ nombre: 'Np300', marca: 'Nissan' },
{ nombre: 'Pathfinder', marca: 'Nissan' },
{ nombre: 'Qashqai', marca: 'Nissan' },
{ nombre: 'Terrano', marca: 'Nissan' },

// === SEDANES/HATCHBACKS ===
{ nombre: 'Almera', marca: 'Nissan' },
{ nombre: 'Altima', marca: 'Nissan' },
{ nombre: 'Maxima', marca: 'Nissan' },
{ nombre: 'Note', marca: 'Nissan' },
{ nombre: 'Sentra', marca: 'Nissan' },
{ nombre: 'Sunny', marca: 'Nissan' },
{ nombre: 'Tiida', marca: 'Nissan' },
{ nombre: 'Versa', marca: 'Nissan' },

// === SUVs/CROSSOVERS ===
{ nombre: 'Armada', marca: 'Nissan' },
{ nombre: 'Juke', marca: 'Nissan' },
{ nombre: 'Murano', marca: 'Nissan' },
{ nombre: 'Patrol', marca: 'Nissan' },
{ nombre: 'Rogue', marca: 'Nissan' },
{ nombre: 'X-Terra', marca: 'Nissan' },
{ nombre: 'X-Trail', marca: 'Nissan' },

// === PICKUPS/COMERCIALES ===
{ nombre: 'D21', marca: 'Nissan' },
{ nombre: 'D22', marca: 'Nissan' },
{ nombre: 'Frontier', marca: 'Nissan' },
{ nombre: 'Hardbody', marca: 'Nissan' },
{ nombre: 'Titan', marca: 'Nissan' },
{ nombre: 'Urvan', marca: 'Nissan' },
{ nombre: 'Vanette', marca: 'Nissan' },

// === DEPORTIVOS/PERFORMANCE ===
{ nombre: 'Gt-R', marca: 'Nissan' },
{ nombre: 'Silvia', marca: 'Nissan' },
{ nombre: 'Skyline', marca: 'Nissan' },

// === CLÁSICOS/HISTÓRICOS ===
{ nombre: 'B13', marca: 'Nissan' },
{ nombre: 'B14', marca: 'Nissan' },
{ nombre: 'B15', marca: 'Nissan' },
{ nombre: 'Cedric', marca: 'Nissan' },
{ nombre: 'Primera', marca: 'Nissan' },
{ nombre: 'Pulsar', marca: 'Nissan' },
{ nombre: 'Tsuru', marca: 'Nissan' },

// === ELÉCTRICOS/HÍBRIDOS ===
{ nombre: 'Leaf', marca: 'Nissan' },

// === OTROS MODELOS ===
{ nombre: 'Cube', marca: 'Nissan' },
{ nombre: 'Livina', marca: 'Nissan' },
{ nombre: 'Micra', marca: 'Nissan' },
{ nombre: 'Platina', marca: 'Nissan' },
{ nombre: 'Quest', marca: 'Nissan' },
{ nombre: 'Stanza', marca: 'Nissan' },
{ nombre: 'Tsubame', marca: 'Nissan' },

// Modelos de Opel - LISTA COMPLETA (40 modelos)
// Incluye modelos que comienzan con números como solicitado

// === MODELOS QUE COMIENZAN CON NÚMEROS ===
{ nombre: '1900', marca: 'Opel' },
{ nombre: '2000 E', marca: 'Opel' },

// === COMPACTOS/HATCHBACKS ===
{ nombre: 'Adam', marca: 'Opel' },
{ nombre: 'Agila', marca: 'Opel' },
{ nombre: 'Corsa', marca: 'Opel' },
{ nombre: 'Corsa A', marca: 'Opel' },
{ nombre: 'Corsa B', marca: 'Opel' },
{ nombre: 'Corsa C', marca: 'Opel' },
{ nombre: 'Corsa D', marca: 'Opel' },
{ nombre: 'Corsa E', marca: 'Opel' },
{ nombre: 'Karl', marca: 'Opel' },
{ nombre: 'Tigra', marca: 'Opel' },

// === SEDANES/FAMILIARES ===
{ nombre: 'Astra', marca: 'Opel' },
{ nombre: 'Astra F', marca: 'Opel' },
{ nombre: 'Astra G', marca: 'Opel' },
{ nombre: 'Astra H', marca: 'Opel' },
{ nombre: 'Astra J', marca: 'Opel' },
{ nombre: 'Astra K', marca: 'Opel' },
{ nombre: 'Insignia', marca: 'Opel' },
{ nombre: 'Insignia A', marca: 'Opel' },
{ nombre: 'Insignia B', marca: 'Opel' },
{ nombre: 'Vectra', marca: 'Opel' },
{ nombre: 'Vectra A', marca: 'Opel' },
{ nombre: 'Vectra B', marca: 'Opel' },
{ nombre: 'Vectra C', marca: 'Opel' },

// === SUVs/CROSSOVERS ===
{ nombre: 'Antara', marca: 'Opel' },
{ nombre: 'Crossland X', marca: 'Opel' },
{ nombre: 'Grandland X', marca: 'Opel' },
{ nombre: 'Mokka', marca: 'Opel' },
{ nombre: 'Mokka X', marca: 'Opel' },

// === DEPORTIVOS/COUPÉS ===
{ nombre: 'Calibra', marca: 'Opel' },
{ nombre: 'GT', marca: 'Opel' },
{ nombre: 'Speedster', marca: 'Opel' },

// === COMERCIALES/VANS ===
{ nombre: 'Combo', marca: 'Opel' },
{ nombre: 'Movano', marca: 'Opel' },
{ nombre: 'Vivaro', marca: 'Opel' },

// === CLÁSICOS/HISTÓRICOS ===
{ nombre: 'Ascona', marca: 'Opel' },
{ nombre: 'Kadett', marca: 'Opel' },
{ nombre: 'Manta', marca: 'Opel' },
{ nombre: 'Omega', marca: 'Opel' },
{ nombre: 'Record', marca: 'Opel' },
{ nombre: 'Senator', marca: 'Opel' },

// === ESPECIALES ===
{ nombre: 'Ampera', marca: 'Opel' },


// Modelos de Peugeot - LISTA COMPLETA (41 modelos)
// Incluye 29 modelos que comienzan con números como solicitado

// === MODELOS QUE COMIENZAN CON NÚMEROS (29 modelos) ===
// Serie 100
{ nombre: '106', marca: 'Peugeot' },
{ nombre: '107', marca: 'Peugeot' },
{ nombre: '108', marca: 'Peugeot' },

// Serie 200
{ nombre: '205', marca: 'Peugeot' },
{ nombre: '206', marca: 'Peugeot' },
{ nombre: '206 Sw', marca: 'Peugeot' },
{ nombre: '207', marca: 'Peugeot' },
{ nombre: '208', marca: 'Peugeot' },

// Serie 300
{ nombre: '301', marca: 'Peugeot' },
{ nombre: '306', marca: 'Peugeot' },
{ nombre: '307', marca: 'Peugeot' },
{ nombre: '307 Sw', marca: 'Peugeot' },
{ nombre: '308', marca: 'Peugeot' },

// Serie 400
{ nombre: '404', marca: 'Peugeot' },
{ nombre: '405', marca: 'Peugeot' },
{ nombre: '406', marca: 'Peugeot' },
{ nombre: '407', marca: 'Peugeot' },
{ nombre: '407 Coupe', marca: 'Peugeot' },
{ nombre: '407 Sw', marca: 'Peugeot' },

// Serie 500
{ nombre: '504', marca: 'Peugeot' },
{ nombre: '505', marca: 'Peugeot' },
{ nombre: '508', marca: 'Peugeot' },

// Serie 600
{ nombre: '605', marca: 'Peugeot' },
{ nombre: '607', marca: 'Peugeot' },

// Serie 800
{ nombre: '806', marca: 'Peugeot' },

// SUVs con números
{ nombre: '2008', marca: 'Peugeot' },
{ nombre: '3008', marca: 'Peugeot' },
{ nombre: '4008', marca: 'Peugeot' },
{ nombre: '5008', marca: 'Peugeot' },

// === MODELOS CON NOMBRES (12 modelos) ===
// Comerciales
{ nombre: 'Bipper', marca: 'Peugeot' },
{ nombre: 'Boxer', marca: 'Peugeot' },
{ nombre: 'Expert', marca: 'Peugeot' },
{ nombre: 'Partner', marca: 'Peugeot' },
{ nombre: 'Partner Origin', marca: 'Peugeot' },
{ nombre: 'Rifter', marca: 'Peugeot' },
{ nombre: 'Tepee', marca: 'Peugeot' },
{ nombre: 'Traveller', marca: 'Peugeot' },

// Pickups/SUVs
{ nombre: 'Landtrek', marca: 'Peugeot' },

// Deportivos
{ nombre: 'Rcz', marca: 'Peugeot' },

// Eléctricos
{ nombre: 'E-2008', marca: 'Peugeot' },

// Otros
{ nombre: 'Xr', marca: 'Peugeot' },


// Modelos de Porsche - LISTA COMPLETA (49 modelos)
{ nombre: '718 Boxster', marca: 'Porsche' },
{ nombre: '718 Boxster T', marca: 'Porsche' },
{ nombre: '718 Cayman', marca: 'Porsche' },
{ nombre: '718 Cayman GT4 RS', marca: 'Porsche' },
{ nombre: '718 Cayman GTS', marca: 'Porsche' },
{ nombre: '718 Cayman S', marca: 'Porsche' },
{ nombre: '718 Cayman T', marca: 'Porsche' },
{ nombre: '718 Spyder', marca: 'Porsche' },
{ nombre: '718 Spyder RS', marca: 'Porsche' },
{ nombre: '911 Carrera', marca: 'Porsche' },
{ nombre: '911 Carrera 4', marca: 'Porsche' },
{ nombre: '911 Carrera 4 Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera 4 GTS', marca: 'Porsche' },
{ nombre: '911 Carrera 4 GTS Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera 4S', marca: 'Porsche' },
{ nombre: '911 Carrera 4S Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera GTS', marca: 'Porsche' },
{ nombre: '911 Carrera GTS Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera S', marca: 'Porsche' },
{ nombre: '911 Carrera S Cabriolet', marca: 'Porsche' },
{ nombre: '911 Carrera T', marca: 'Porsche' },
{ nombre: '911 Dakar', marca: 'Porsche' },
{ nombre: '911 GT3', marca: 'Porsche' },
{ nombre: '911 GT3 RS', marca: 'Porsche' },
{ nombre: '911 S/T', marca: 'Porsche' },
{ nombre: '911 Targa', marca: 'Porsche' },
{ nombre: '911 Targa 4', marca: 'Porsche' },
{ nombre: '911 Targa 4 GTS', marca: 'Porsche' },
{ nombre: '911 Targa 4S', marca: 'Porsche' },
{ nombre: '911 Targa 50 Edition Years', marca: 'Porsche' },
{ nombre: '911 Turbo', marca: 'Porsche' },
{ nombre: '911 Turbo Cabriolet', marca: 'Porsche' },
{ nombre: '911 Turbo S', marca: 'Porsche' },
{ nombre: '911 Turbo S Cabriolet', marca: 'Porsche' },
{ nombre: '928', marca: 'Porsche' },
{ nombre: 'Boxster', marca: 'Porsche' },
{ nombre: 'Boxster 718 GTS', marca: 'Porsche' },
{ nombre: 'Cayenne', marca: 'Porsche' },
{ nombre: 'Cayenne Coupé', marca: 'Porsche' },
{ nombre: 'Cayenne E-Hybrid', marca: 'Porsche' },
{ nombre: 'Cayenne E-Hybrid Coupé', marca: 'Porsche' },
{ nombre: 'Cayenne S', marca: 'Porsche' },
{ nombre: 'Cayenne S Coupé', marca: 'Porsche' },
{ nombre: 'Cayenne S E-Hybrid', marca: 'Porsche' },
{ nombre: 'Cayenne Turbo E-Hybrid', marca: 'Porsche' },
{ nombre: 'Cayman', marca: 'Porsche' },
{ nombre: 'Cayman GT4', marca: 'Porsche' },
{ nombre: 'Macan', marca: 'Porsche' },
{ nombre: 'Macan GTS', marca: 'Porsche' },
{ nombre: 'Macan S', marca: 'Porsche' },
{ nombre: 'Macan Turbo', marca: 'Porsche' },
{ nombre: 'Panamera', marca: 'Porsche' },
{ nombre: 'Panamera 4 E-Hybrid', marca: 'Porsche' },
{ nombre: 'Panamera 4S E-Hybrid', marca: 'Porsche' },
{ nombre: 'Panamera GTS', marca: 'Porsche' },
{ nombre: 'Panamera Turbo S', marca: 'Porsche' },
{ nombre: 'Panamera Turbo S E-Hybrid', marca: 'Porsche' },
{ nombre: 'Taycan', marca: 'Porsche' },

// Modelos de Renault - LISTA COMPLETA (52 modelos)
{ nombre: '19', marca: 'Renault' },
{ nombre: 'Alaskan', marca: 'Renault' },
{ nombre: 'Arkana', marca: 'Renault' },
{ nombre: 'Captur', marca: 'Renault' },
{ nombre: 'Clio', marca: 'Renault' },
{ nombre: 'Clio 2', marca: 'Renault' },
{ nombre: 'Dokker', marca: 'Renault' },
{ nombre: 'Dokker Stepway', marca: 'Renault' },
{ nombre: 'Duster', marca: 'Renault' },
{ nombre: 'Espace', marca: 'Renault' },
{ nombre: 'Express', marca: 'Renault' },
{ nombre: 'Fluence', marca: 'Renault' },
{ nombre: 'Grand Scenic', marca: 'Renault' },
{ nombre: 'Kadjar', marca: 'Renault' },
{ nombre: 'Kango Express Diesel', marca: 'Renault' },
{ nombre: 'Kango Express Diesel Cerrado', marca: 'Renault' },
{ nombre: 'Kango Express Diesel Company', marca: 'Renault' },
{ nombre: 'Kango Express Diesel Dh', marca: 'Renault' },
{ nombre: 'Kangoo', marca: 'Renault' },
{ nombre: 'Kangoo Express', marca: 'Renault' },
{ nombre: 'Kiger', marca: 'Renault' },
{ nombre: 'Koleos', marca: 'Renault' },
{ nombre: 'Kwid', marca: 'Renault' },
{ nombre: 'Laguna', marca: 'Renault' },
{ nombre: 'Laguna II', marca: 'Renault' },
{ nombre: 'Laguna Nevada', marca: 'Renault' },
{ nombre: 'Latitude', marca: 'Renault' },
{ nombre: 'Lodgy', marca: 'Renault' },
{ nombre: 'Lodgy Stepway', marca: 'Renault' },
{ nombre: 'Logan', marca: 'Renault' },
{ nombre: 'Logan Stepway', marca: 'Renault' },
{ nombre: 'Master', marca: 'Renault' },
{ nombre: 'Megane', marca: 'Renault' },
{ nombre: 'Megane E-Tech', marca: 'Renault' },
{ nombre: 'Megane II', marca: 'Renault' },
{ nombre: 'Megane III', marca: 'Renault' },
{ nombre: 'Megane Rs', marca: 'Renault' },
{ nombre: 'Modus', marca: 'Renault' },
{ nombre: 'Oroch', marca: 'Renault' },
{ nombre: 'R10', marca: 'Renault' },
{ nombre: 'R11', marca: 'Renault' },
{ nombre: 'R12', marca: 'Renault' },
{ nombre: 'R15', marca: 'Renault' },
{ nombre: 'R16', marca: 'Renault' },
{ nombre: 'R17', marca: 'Renault' },
{ nombre: 'R18', marca: 'Renault' },
{ nombre: 'R19', marca: 'Renault' },
{ nombre: 'R21', marca: 'Renault' },
{ nombre: 'R25', marca: 'Renault' },
{ nombre: 'R4', marca: 'Renault' },
{ nombre: 'R5', marca: 'Renault' },
{ nombre: 'R6', marca: 'Renault' },
{ nombre: 'R8', marca: 'Renault' },
{ nombre: 'R9', marca: 'Renault' },
{ nombre: 'Safrane', marca: 'Renault' },
{ nombre: 'Sandero', marca: 'Renault' },
{ nombre: 'Scenic', marca: 'Renault' },
{ nombre: 'Scenic I', marca: 'Renault' },
{ nombre: 'Scenic II', marca: 'Renault' },
{ nombre: 'Spider', marca: 'Renault' },
{ nombre: 'Symbol', marca: 'Renault' },
{ nombre: 'Talisman', marca: 'Renault' },
{ nombre: 'Thalia', marca: 'Renault' },
{ nombre: 'Traffic', marca: 'Renault' },
{ nombre: 'Trafic', marca: 'Renault' },
{ nombre: 'Triber', marca: 'Renault' },
{ nombre: 'Twingo', marca: 'Renault' },
{ nombre: 'Twizy', marca: 'Renault' },
{ nombre: 'Vel Satis', marca: 'Renault' },
{ nombre: 'Wind', marca: 'Renault' },
{ nombre: 'Zoe', marca: 'Renault' },

// Modelos de SsangYong - LISTA COMPLETA (16 modelos)
{ nombre: 'Actyon', marca: 'SsangYong' },
{ nombre: 'Actyon Sports', marca: 'SsangYong' },
{ nombre: 'Chairman', marca: 'SsangYong' },
{ nombre: 'Grand Musso', marca: 'SsangYong' },
{ nombre: 'Korando', marca: 'SsangYong' },
{ nombre: 'Kyron', marca: 'SsangYong' },
{ nombre: 'Musso', marca: 'SsangYong' },
{ nombre: 'Musso Sports', marca: 'SsangYong' },
{ nombre: 'Rexton', marca: 'SsangYong' },
{ nombre: 'Rexton W', marca: 'SsangYong' },
{ nombre: 'Rodius', marca: 'SsangYong' },
{ nombre: 'Stavic', marca: 'SsangYong' },
{ nombre: 'Tivoli', marca: 'SsangYong' },
{ nombre: 'Torres', marca: 'SsangYong' },
{ nombre: 'Torres Evx', marca: 'SsangYong' },
{ nombre: 'Xlv', marca: 'SsangYong' },

// Modelos de Subaru - LISTA COMPLETA (29 modelos)
{ nombre: '360', marca: 'Subaru' },
{ nombre: 'Alcyone', marca: 'Subaru' },
{ nombre: 'B9 Tribeca', marca: 'Subaru' },
{ nombre: 'Baja', marca: 'Subaru' },
{ nombre: 'Brz', marca: 'Subaru' },
{ nombre: 'Crosstrek', marca: 'Subaru' },
{ nombre: 'Domingo', marca: 'Subaru' },
{ nombre: 'Evoltis', marca: 'Subaru' },
{ nombre: 'Forester', marca: 'Subaru' },
{ nombre: 'Impreza', marca: 'Subaru' },
{ nombre: 'Justy', marca: 'Subaru' },
{ nombre: 'Legacy', marca: 'Subaru' },
{ nombre: 'Leone', marca: 'Subaru' },
{ nombre: 'Libero', marca: 'Subaru' },
{ nombre: 'Liberty', marca: 'Subaru' },
{ nombre: 'Loyale', marca: 'Subaru' },
{ nombre: 'Mv', marca: 'Subaru' },
{ nombre: 'New Legacy', marca: 'Subaru' },
{ nombre: 'New XV', marca: 'Subaru' },
{ nombre: 'Outback', marca: 'Subaru' },
{ nombre: 'Pleo', marca: 'Subaru' },
{ nombre: 'R1', marca: 'Subaru' },
{ nombre: 'R2', marca: 'Subaru' },
{ nombre: 'Rex', marca: 'Subaru' },
{ nombre: 'Sambar', marca: 'Subaru' },
{ nombre: 'Stella', marca: 'Subaru' },
{ nombre: 'Svx', marca: 'Subaru' },
{ nombre: 'Traviq', marca: 'Subaru' },
{ nombre: 'Tribeca', marca: 'Subaru' },
{ nombre: 'Tutto', marca: 'Subaru' },
{ nombre: 'Vivio', marca: 'Subaru' },
{ nombre: 'Wrx', marca: 'Subaru' },
{ nombre: 'Wrx Sti', marca: 'Subaru' },
{ nombre: 'Xv', marca: 'Subaru' },

// Modelos de Suzuki - LISTA COMPLETA (36 modelos)
{ nombre: 'Aerio', marca: 'Suzuki' },
{ nombre: 'Alto', marca: 'Suzuki' },
{ nombre: 'Apv', marca: 'Suzuki' },
{ nombre: 'Apv Furgon', marca: 'Suzuki' },
{ nombre: 'Apv Pick Up', marca: 'Suzuki' },
{ nombre: 'Baleno', marca: 'Suzuki' },
{ nombre: 'Carry', marca: 'Suzuki' },
{ nombre: 'Celerio', marca: 'Suzuki' },
{ nombre: 'Ciaz', marca: 'Suzuki' },
{ nombre: 'Dzire', marca: 'Suzuki' },
{ nombre: 'Ertiga', marca: 'Suzuki' },
{ nombre: 'Fronx', marca: 'Suzuki' },
{ nombre: 'Furgon', marca: 'Suzuki' },
{ nombre: 'Grand Nomade', marca: 'Suzuki' },
{ nombre: 'Grand Vitara', marca: 'Suzuki' },
{ nombre: 'Ignis', marca: 'Suzuki' },
{ nombre: 'Jimny', marca: 'Suzuki' },
{ nombre: 'Kizashi', marca: 'Suzuki' },
{ nombre: 'Liana', marca: 'Suzuki' },
{ nombre: 'Maruti', marca: 'Suzuki' },
{ nombre: 'Mastervan', marca: 'Suzuki' },
{ nombre: 'Nomade', marca: 'Suzuki' },
{ nombre: 'Pick Up', marca: 'Suzuki' },
{ nombre: 'S-Cross', marca: 'Suzuki' },
{ nombre: 'S-Presso', marca: 'Suzuki' },
{ nombre: 'Samurai', marca: 'Suzuki' },
{ nombre: 'Sidekick', marca: 'Suzuki' },
{ nombre: 'Swift', marca: 'Suzuki' },
{ nombre: 'Swift Dzire', marca: 'Suzuki' },
{ nombre: 'Swift Hybrid', marca: 'Suzuki' },
{ nombre: 'Swift Sport', marca: 'Suzuki' },
{ nombre: 'Sx4', marca: 'Suzuki' },
{ nombre: 'Sx4 S-Cross', marca: 'Suzuki' },
{ nombre: 'Vitara', marca: 'Suzuki' },
{ nombre: 'Wagon R', marca: 'Suzuki' },
{ nombre: 'Xl7', marca: 'Suzuki' },


// Modelos de Toyota - LISTA COMPLETA (45 modelos)
{ nombre: '4Runner', marca: 'Toyota' },
{ nombre: '86', marca: 'Toyota' },
{ nombre: 'Advantage', marca: 'Toyota' },
{ nombre: 'Auris', marca: 'Toyota' },
{ nombre: 'Avalon', marca: 'Toyota' },
{ nombre: 'Avensis', marca: 'Toyota' },
{ nombre: 'Aygo', marca: 'Toyota' },
{ nombre: 'C-Hr', marca: 'Toyota' },
{ nombre: 'Camry', marca: 'Toyota' },
{ nombre: 'Carina', marca: 'Toyota' },
{ nombre: 'Celica', marca: 'Toyota' },
{ nombre: 'Corolla', marca: 'Toyota' },
{ nombre: 'Corolla Cross', marca: 'Toyota' },
{ nombre: 'Corolla Fielder', marca: 'Toyota' },
{ nombre: 'Corolla Sport', marca: 'Toyota' },
{ nombre: 'Corona', marca: 'Toyota' },
{ nombre: 'Cressida', marca: 'Toyota' },
{ nombre: 'Dyna', marca: 'Toyota' },
{ nombre: 'Echo', marca: 'Toyota' },
{ nombre: 'Fj Cruiser', marca: 'Toyota' },
{ nombre: 'Fortuner', marca: 'Toyota' },
{ nombre: 'Ft-86', marca: 'Toyota' },
{ nombre: 'Hiace', marca: 'Toyota' },
{ nombre: 'Highlander', marca: 'Toyota' },
{ nombre: 'Hilux', marca: 'Toyota' },
{ nombre: 'Land Cruiser', marca: 'Toyota' },
{ nombre: 'Land Cruiser Prado', marca: 'Toyota' },
{ nombre: 'Landcruiser Prado', marca: 'Toyota' },
{ nombre: 'Lite', marca: 'Toyota' },
{ nombre: 'Matrix', marca: 'Toyota' },
{ nombre: 'Mr2', marca: 'Toyota' },
{ nombre: 'Paseo', marca: 'Toyota' },
{ nombre: 'Previa', marca: 'Toyota' },
{ nombre: 'Prius', marca: 'Toyota' },
{ nombre: 'Prius C', marca: 'Toyota' },
{ nombre: 'Raize', marca: 'Toyota' },
{ nombre: 'Rav4', marca: 'Toyota' },
{ nombre: 'Rush', marca: 'Toyota' },
{ nombre: 'Sequoia', marca: 'Toyota' },
{ nombre: 'Sienna', marca: 'Toyota' },
{ nombre: 'Starlet', marca: 'Toyota' },
{ nombre: 'Supra', marca: 'Toyota' },
{ nombre: 'T100', marca: 'Toyota' },
{ nombre: 'Tacoma', marca: 'Toyota' },
{ nombre: 'Tercel', marca: 'Toyota' },
{ nombre: 'Terios', marca: 'Toyota' },
{ nombre: 'Tundra', marca: 'Toyota' },
{ nombre: 'Urban Cruiser', marca: 'Toyota' },
{ nombre: 'Venza', marca: 'Toyota' },
{ nombre: 'Yaris', marca: 'Toyota' },
{ nombre: 'Yaris Cross', marca: 'Toyota' },
{ nombre: 'Yaris Sport', marca: 'Toyota' },
{ nombre: 'Zelas', marca: 'Toyota' },


// Modelos de Volkswagen - LISTA COMPLETA (44 modelos)
{ nombre: 'Amarok', marca: 'Volkswagen' },
{ nombre: 'Atlas', marca: 'Volkswagen' },
{ nombre: 'Beelte', marca: 'Volkswagen' },
{ nombre: 'Beetle', marca: 'Volkswagen' },
{ nombre: 'Bora', marca: 'Volkswagen' },
{ nombre: 'Caddy', marca: 'Volkswagen' },
{ nombre: 'Caravelle', marca: 'Volkswagen' },
{ nombre: 'Cc', marca: 'Volkswagen' },
{ nombre: 'Crafter', marca: 'Volkswagen' },
{ nombre: 'Escarabajo', marca: 'Volkswagen' },
{ nombre: 'Fox', marca: 'Volkswagen' },
{ nombre: 'Gol', marca: 'Volkswagen' },
{ nombre: 'Golf', marca: 'Volkswagen' },
{ nombre: 'Gti', marca: 'Volkswagen' },
{ nombre: 'Jetta', marca: 'Volkswagen' },
{ nombre: 'Multivan', marca: 'Volkswagen' },
{ nombre: 'New Beetle', marca: 'Volkswagen' },
{ nombre: 'Nivus', marca: 'Volkswagen' },
{ nombre: 'Passat', marca: 'Volkswagen' },
{ nombre: 'Passat CC', marca: 'Volkswagen' },
{ nombre: 'Polo', marca: 'Volkswagen' },
{ nombre: 'Saveiro', marca: 'Volkswagen' },
{ nombre: 'Scirocco', marca: 'Volkswagen' },
{ nombre: 'Suran', marca: 'Volkswagen' },
{ nombre: 'T-Cross', marca: 'Volkswagen' },
{ nombre: 'Taos', marca: 'Volkswagen' },
{ nombre: 'The Beetle', marca: 'Volkswagen' },
{ nombre: 'Tiguan', marca: 'Volkswagen' },
{ nombre: 'Tiguan Allspace', marca: 'Volkswagen' },
{ nombre: 'Touareg', marca: 'Volkswagen' },
{ nombre: 'Transporter', marca: 'Volkswagen' },
{ nombre: 'Vento', marca: 'Volkswagen' },
{ nombre: 'Virtus', marca: 'Volkswagen' },
{ nombre: 'Voyage', marca: 'Volkswagen' },

// Modelos de Volvo - LISTA COMPLETA (25 modelos)
{ nombre: '122', marca: 'Volvo' },
{ nombre: '164', marca: 'Volvo' },
{ nombre: '240', marca: 'Volvo' },
{ nombre: '244', marca: 'Volvo' },
{ nombre: '340', marca: 'Volvo' },
{ nombre: '460', marca: 'Volvo' },
{ nombre: '740', marca: 'Volvo' },
{ nombre: '850', marca: 'Volvo' },
{ nombre: 'B 18', marca: 'Volvo' },
{ nombre: 'C30', marca: 'Volvo' },
{ nombre: 'C70', marca: 'Volvo' },
{ nombre: 'S40', marca: 'Volvo' },
{ nombre: 'S60', marca: 'Volvo' },
{ nombre: 'S60 Cross Country', marca: 'Volvo' },
{ nombre: 'S80', marca: 'Volvo' },
{ nombre: 'S90', marca: 'Volvo' },
{ nombre: 'V40', marca: 'Volvo' },
{ nombre: 'V40 1.6 T4 Comfort', marca: 'Volvo' },
{ nombre: 'V40 Cross Country', marca: 'Volvo' },
{ nombre: 'V50', marca: 'Volvo' },
{ nombre: 'V60', marca: 'Volvo' },
{ nombre: 'V60 Cross Country', marca: 'Volvo' },
{ nombre: 'V70', marca: 'Volvo' },
{ nombre: 'V90', marca: 'Volvo' },
{ nombre: 'V90 Cross Country', marca: 'Volvo' },
{ nombre: 'Xc40', marca: 'Volvo' },
{ nombre: 'Xc60', marca: 'Volvo' },
{ nombre: 'Xc70', marca: 'Volvo' },
{ nombre: 'Xc90', marca: 'Volvo' },

// Modelos de Yamaha - LISTA COMPLETA (87+ modelos)
{ nombre: '125Cc', marca: 'Yamaha' },
{ nombre: '150Cc', marca: 'Yamaha' },
{ nombre: '155Cc', marca: 'Yamaha' },
{ nombre: '155 cc', marca: 'Yamaha' },
{ nombre: '600', marca: 'Yamaha' },
{ nombre: 'Bolt', marca: 'Yamaha' },
{ nombre: 'Bolt950', marca: 'Yamaha' },
{ nombre: 'Bws', marca: 'Yamaha' },
{ nombre: 'Chopper', marca: 'Yamaha' },
{ nombre: 'CV50 Beluga', marca: 'Yamaha' },
{ nombre: 'Beluga 50', marca: 'Yamaha' },
{ nombre: 'Cygnus Z Xa 125', marca: 'Yamaha' },
{ nombre: 'Cygnus-Z', marca: 'Yamaha' },
{ nombre: 'Enticer', marca: 'Yamaha' },
{ nombre: 'Especial 850xs', marca: 'Yamaha' },
{ nombre: 'Fazer 1000 Fz1', marca: 'Yamaha' },
{ nombre: 'Fz', marca: 'Yamaha' },
{ nombre: 'Fz 150', marca: 'Yamaha' },
{ nombre: 'Fz 25', marca: 'Yamaha' },
{ nombre: 'Fz 250', marca: 'Yamaha' },
{ nombre: 'Fz-16', marca: 'Yamaha' },
{ nombre: 'Fz1', marca: 'Yamaha' },
{ nombre: 'Fz6 S2', marca: 'Yamaha' },
{ nombre: 'Fz8', marca: 'Yamaha' },
{ nombre: 'Fzn 150', marca: 'Yamaha' },
{ nombre: 'Fzn 150 Fi', marca: 'Yamaha' },
{ nombre: 'Fz N', marca: 'Yamaha' },
{ nombre: 'Fzr', marca: 'Yamaha' },
{ nombre: 'Midnight Star 950', marca: 'Yamaha' },
{ nombre: 'Mt-03', marca: 'Yamaha' },
{ nombre: 'Mt-07', marca: 'Yamaha' },
{ nombre: 'Mt-09', marca: 'Yamaha' },
{ nombre: 'Mt-09 Tracer', marca: 'Yamaha' },
{ nombre: 'Mt-10', marca: 'Yamaha' },
{ nombre: 'Nmax', marca: 'Yamaha' },
{ nombre: 'Nmax 150', marca: 'Yamaha' },
{ nombre: 'Nmax 155', marca: 'Yamaha' },
{ nombre: 'R1', marca: 'Yamaha' },
{ nombre: 'R1 Yzfr1 Yzf R1', marca: 'Yamaha' },
{ nombre: 'R3', marca: 'Yamaha' },
{ nombre: 'R3 320', marca: 'Yamaha' },
{ nombre: 'R3 Yzf', marca: 'Yamaha' },
{ nombre: 'R3A', marca: 'Yamaha' },
{ nombre: 'R6', marca: 'Yamaha' },
{ nombre: 'R15', marca: 'Yamaha' },
{ nombre: 'R15 V3', marca: 'Yamaha' },
{ nombre: 'Raptor', marca: 'Yamaha' },
{ nombre: 'Stryker', marca: 'Yamaha' },
{ nombre: 'Super Tenere 1200 Z', marca: 'Yamaha' },
{ nombre: 'T Max', marca: 'Yamaha' },
{ nombre: 'Ttr-110', marca: 'Yamaha' },
{ nombre: 'V Star', marca: 'Yamaha' },
{ nombre: 'V Star 1300', marca: 'Yamaha' },
{ nombre: 'V-Max', marca: 'Yamaha' },
{ nombre: 'Virago', marca: 'Yamaha' },
{ nombre: 'Vstar', marca: 'Yamaha' },
{ nombre: 'Vstar 250', marca: 'Yamaha' },
{ nombre: 'Warrior', marca: 'Yamaha' },
{ nombre: 'Wr', marca: 'Yamaha' },
{ nombre: 'Wr-450F', marca: 'Yamaha' },
{ nombre: 'Wrf 450', marca: 'Yamaha' },
{ nombre: 'XA125', marca: 'Yamaha' },
{ nombre: 'Xa 125', marca: 'Yamaha' },
{ nombre: 'Xj6f', marca: 'Yamaha' },
{ nombre: 'Xj6-F', marca: 'Yamaha' },
{ nombre: 'XMax 300', marca: 'Yamaha' },
{ nombre: 'Xs', marca: 'Yamaha' },
{ nombre: 'Xsr700', marca: 'Yamaha' },
{ nombre: 'Xt 1200 Supertenere', marca: 'Yamaha' },
{ nombre: 'Xt-1200Z', marca: 'Yamaha' },
{ nombre: 'Xt660', marca: 'Yamaha' },
{ nombre: 'Xvs', marca: 'Yamaha' },
{ nombre: 'Xvs 650 Star', marca: 'Yamaha' },
{ nombre: 'Yamaha R3', marca: 'Yamaha' },
{ nombre: 'Yba', marca: 'Yamaha' },
{ nombre: 'Yfz 450R', marca: 'Yamaha' },
{ nombre: 'Yfz R15', marca: 'Yamaha' },
{ nombre: 'Yz', marca: 'Yamaha' },
{ nombre: 'Yz 250', marca: 'Yamaha' },
{ nombre: 'Yz 250 Fx', marca: 'Yamaha' },
{ nombre: 'Yz 250X', marca: 'Yamaha' },
{ nombre: 'Yz 450 Fx', marca: 'Yamaha' },
{ nombre: 'Yz-250F', marca: 'Yamaha' },
{ nombre: 'Yzf R15', marca: 'Yamaha' },
{ nombre: 'Yzf R3', marca: 'Yamaha' },
{ nombre: 'Yzf R3 320 CC', marca: 'Yamaha' },
{ nombre: 'Yzf-R1', marca: 'Yamaha' },
{ nombre: 'Yzf-R3a', marca: 'Yamaha' },
{ nombre: 'Yzf-R6', marca: 'Yamaha' }

    ];

    // Convertir cada modelo para que tenga marcaId
    const now = new Date();
    const modelosFinal = modelos.map(({ nombre, marca }) => {
      const marcaId = marcaIdMap[marca];
      if (!marcaId) {
        throw new Error(`Marca no encontrada en la base de datos: ${marca}`);
      }

      return {
        nombre,
        marcaId,
        createdAt: now,
        updatedAt: now
      };
    });

   // 🔍 Mostrar en consola los modelos que se van a insertar
   console.log('Modelos que se van a insertar:', modelosFinal);

   // Insertar con manejo de errores
   try {
     await queryInterface.bulkInsert('Modelos', modelosFinal, {});
   } catch (error) {
     console.error('❌ Error al insertar modelos:', error);
   }
 },

 async down(queryInterface, Sequelize) {
   await queryInterface.bulkDelete('Modelos', null, {});
 }
};